### ISSUE TITLE
Знакомство с GraphQL

### ISSUE THREAD

**Issue by Mirved64** [atls-academy/Mirved64.github.io#20]
## Цель

Ознакомиться с **GraphQL**, инструментом коммуникации между front-end и back-end.

### План
- [x] Коммуникация с сервером - как и с помощью чего [(MDN 1)](https://developer.mozilla.org/ru/docs/Learn/Server-side/First_steps/Introduction) [(MDN 2)](https://developer.mozilla.org/ru/docs/Learn/Server-side/First_steps/Client-Server_overview) [(github RU, до "Веб-сервер")](https://amiskov.github.io/frontend-handbook/web/#что-происходит-при-http-запросе)
- Факультативно: покидать REST API запросы к [Star Wars API](https://swapi.dev) с помощью [`curl`](https://www.baeldung.com/curl-rest)
- [x] [**REST**](https://habr.com/ru/articles/483202/) и [**GraphQL**](https://graphql.org/learn/): сходства и различия [(aws.amazon.com RU)](https://aws.amazon.com/ru/compare/the-difference-between-graphql-and-rest/) [(habr RU)](https://habr.com/ru/companies/rshb/articles/593115/)
- [x] Виды запросов/операций (`query`, `mutation`, `subscription`) [(ресурс RU)](https://senior.ua/articles/rest-api-vs-graphql-chto-vybrat-dlya-konkretnogo-proekta) [(hexlet RU)](https://ru.hexlet.io/blog/posts/chto-takoe-graphql-s-osnov-do-pervyh-zaprosov#kak-rabotat-s-serverom-graphql)
- [x] Схема **GraphQL**: формирование запросов ([оф. документация EN](https://graphql.org/learn/schema/))
- [x] [`Apollo Client`](https://www.apollographql.com/docs/): наш инструмент коммуникации с сервером. [(habr RU)](https://habr.com/ru/articles/358292/), [(видео EN)](https://www.youtube.com/watch?v=YyUWW04HwKY)

**Comment by Nelfimov** [comment]
# Задание

Наш эндпоинт: https://wp.api.atls.academy/graphql

Необходимо весь контент проекта получать оттуда, ничего не должно быть зашито в код.

<details>
<summary>Секции</summary>

```graphql
query NewQuery {
  sections {
    nodes {
      content
    }
  }
}
```

</details>

<details>
<summary>FAQ</summary>

```graphql
allFAQ {
  nodes {
    faq {
      answer
      question
    }
  }
}
```

</details>

<details>
<summary>Скиллы, бегущая строка</summary>

```graphql
skills {
  nodes {
    title
  }
}
```

</details>

<details>
<summary>Курсы</summary>

```graphql
courses {
    nodes {
      course {
        title
        description
        label {
          ... on Label {
          id
          title
        }
      }
    }
  }
}
```

</details>


<details>
<summary>Слайдер</summary>

```graphql
query NewQuery {
  slides {
    nodes {
      slider {
        text
        imageDesktop {
          sourceUrl
        }
        imageMobile {
          sourceUrl
        }
      }
    }
  }
}
```

</details>

<details>
<summary>Процесс обучения</summary>

```graphql
query NewQuery {
  processes {
    nodes {
      process {
        description
        title
      }
    }
  }
}
```

</details>

В качестве референса можешь смотреть наш `drum-in`
